### PR TITLE
Do not enforce reading private key, fixes #5

### LINKED ISSUE #5: Signature shows up as "invalid" when private key is not supplied
Given a message, a public key and a signature, it should be possible to verify the signature. However, when no private key is supplied, the UI always shows the signature as "invalid".

The reason for this is that the routine to get the input values from the GUI always ensures that a private key is present. However, for verifying a signature, a private key is not required.

### PR DESCRIPTION
**Pull request by ChrisiPK**
This PR makes reading of the private key optional. This is required for verifying a signature with a public key only.

Fixes #5

### CODE REVIEW

**Comment by zamicol** [comment]
Thank you so much!  

There was a infinite loop bug, and I'm fixing it with a push in a moment.  

Could you do us a huge favor and star this repository on Github?

**Comment by zamicol** [comment]
Pushed up and live!  Thank you for the pull request!

  https://cyphr.me/ed25519_tool/ed.html

You'll likely need to do a hard refresh to see your new changes:  ctrl+shift+r

**Comment by zamicol** [comment]
Thank you again for your pull request.  

If you're interested in this sort of thing, you may find [Coze](https://github.com/Cyphrme/Coze) of interest.  We've put a lot of work into it.  

Like the Ed25519 tool, we've also [published an online tool for Coze](https://cyphr.me/coze_verifier_simple/coze.html) as well.  



We've also built a "power" version that does a lot more magic: https://cyphr.me/coze

For example, to represent ownership or manufacturing of a physical item, https://cyphr.me/ac/wg_epgzYj-qTFt88qPnmkmZPSVgNZhbHyPKT-LmvRdU

A Coze is signed:
https://cyphr.me/coze?verify&input=2smGoe9H-pDcEI_8unpTHjaZvWWpTYiifH3GgcfOfuM


You can also play with the key wallet: https://cyphr.me/wallet


Right now the web version only supports ECDSA because of constraints by Javascript, but we hope to add Ed25519 support soon.

**Comment by ChrisiPK** [comment]
@zamicol Thanks for the fast response! I just checked the web version and it works great!

Coze does sound interesting, I will definitely take a closer look.

**Comment by zamicol** [comment]
We also have a matrix room: https://matrix.to/#/#cyphrmepub:matrix.org which is bridged to the telegram room: https://t.me/+CIfyo0e4MUxntbyM

**Pull request merged**
