### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by AdamT20054**
Fixed a typo. In the page it currently shows "ed5519" instead of "ed25519"

### CODE REVIEW

**Comment by zamicol** [comment]
Thank you so much for the pull request!  

Everything looks good except please remove the file "package-lock.json".

**Comment by AdamT20054** [comment]
Ah my bad, I usually get gitignore to exclude it. Should be all good now

**Comment by zamicol** [comment]
Fantastic!  Thank you!

**Comment by zamicol** [comment]
Adam20054, can you do me a favor and github star this repo?  Thank you so much!

**Comment by AdamT20054** [comment]
Done :)

> Adam20054, can you do me a favor and github star this repo? Thank you so much!

**Comment by zamicol** [comment]
(For some reason, it does not show.🤔)

**Comment by AdamT20054** [comment]
> (For some reason, it does not show.🤔)

Ah my bad, forgot lists are no longer "auto-stared". Sorted :)

**Pull request merged**
